spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lowerCaseServiceId: 'true'
  application:
    name: gateway
  sleuth:
    sampler:
      probability: 1
  zipkin:
    baseUrl: http://localhost:9411/
server:
  port: '8080'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
